apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "mychart.systemlables" . | indent 4}}
data:
  releasename: {{ .Release.Name }}
            
